version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  Build and verify:
    working_directory: ~/angular-showcase
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - run: 
          name: "Installing Dependencies"
          command: npm install
      - run:
          name: "Run tests"
          command: echo "Tests will be added later"
      - run:
          name: "Verifying that application can be built"
          command: npm run build
      - save_cache:
          key: build-artifacts
          paths:
            - ./dist/angular-showcase

  Containerize:
    working_directory: ~/angular-showcase
    docker:
      - image: docker:latest
      - restore_cache:
          key: build-artifacts
      - run:
          name: "Preparing Docker Hub"
          command: cat ./dist/angular-showcase/index.html
      # - run:
      #     name: "Building container"
      #     command: asd
      # - run:
      #     name: "Pushing container"
      #     command: asd

  Deploy to Netlify:
    working_directory: ~/angular-showcase
    docker:
      - image: helgejs/netlify-cli
      - restore_cache:
          key: build-artifacts
      - run:
          name: "Deploying to Netlify"
          command: cat ./dist/angular-showcase/index.html