version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
  docker: circleci/docker@1.7.0
jobs:
  Build:
    working_directory: ~/angular-showcase
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - run: 
          name: "Installing Dependencies"
          command: npm install
      - run:
          name: "Run tests"
          command: echo "Tests will be added later"
      - run:
          name: "Verifying that application can be built"
          command: npm run build
      - save_cache:
          key: build-artifacts
          paths:
            - ./dist/angular-showcase

  Dockerize:
    working_directory: ~/angular-showcase
    docker:
      - image: cimg/base:stable
        auth:
          username: $CI_REGISTRY_USER
          password: $CI_REGISTRY_PASSWORD
    steps:
      - checkout
      - restore_cache:
          key: build-artifacts
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: "Docker Hub Login"
          command: echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin
      - run:
          name: "Docker Build"
          command: docker build --pull -t "$CI_REGISTRY_IMAGE_LOC" .
      - run:
          name: "Docker Push"
          command: docker push "$CI_REGISTRY_IMAGE_LOC"

  Netlify:
    working_directory: ~/angular-showcase
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: build-artifacts      
      - run:
          name: "Preparing Netlify"
          command: npm i -g netlify-cli
      - run:
          name: "Deploying to Netlify"
          command: netlify deploy --auth=$NETLIFY_PAT --dir=./dist/angular-showcase --site=$NETLIFY_SITE_ID --prod --message="$CIRCLE_BUILD_URL"

workflows:
  version: 2
  Continous Integration:
    jobs:
      - Build
      - Dockerize:
          requires:
            - Build
      - Netlify:
          requires:
            - Build