version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
  docker: circleci/docker@1.7.0
jobs:
  Build:
    working_directory: ~/angular-showcase
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - run: 
          name: "Installing Dependencies"
          command: npm install
      - run:
          name: "Run tests"
          command: echo "Tests will be added later"
      - run:
          name: "Verifying that application can be built"
          command: npm run build
      - save_cache:
          key: build-artifacts
          paths:
            - ./dist/angular-showcase

  Dockerize:
    working_directory: ~/angular-showcase
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          key: build-artifacts
      - run:
          name: "Docker Hub Login"
          command: echo "docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY"
      - run:
          name: "Docker Build"
          command: echo "docker build --pull -t "$CI_REGISTRY_IMAGE_LOC" ."
      - run:
          name: "Docker Push"
          command: echo "docker push "$CI_REGISTRY_IMAGE_LOC""

  Netlify:
    working_directory: ~/angular-showcase
    docker:
      - image: helgejs/netlify-cli
    steps:
      - checkout
      - run:
          name: "Fetching Artifacts"
          command: echo "Artifacts"
      - run:
          name: "Deploying to Netlify"
          command: echo "Deploy to Netlify"
        
workflows:
  version: 2
  Continous Integration:
    jobs:
      - Build
      - Dockerize:
          requires:
            - Build
      - Netlify:
          requires:
            - Build