name: Continuous Integration

on:
  push:
    branches:
      - '!main' # Runs on all branches except 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.15
          cache: 'npm'

      - name: Install Node Modules
        run: npm install

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.15
          cache: 'npm'

      - name: Install Node Modules
        run: npm install

      - name: Build
        run: npm run build
